easy_admin:
    site_name: Some name
    design:
        color_scheme: 'dark'
    entities:
        # List the entity class name you want to manage
        Products:
            class: App\Entity\Products
            label: 'Customers'
            list:
              title: '%%entity_label%% listing'
#        - App\Entity\Category
#        - App\Entity\User
